# Generated by Django 5.1.5 on 2025-02-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_expensecategory_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='expense_category',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
